name: Run Tests on Pull Requests

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install Jest dependencies and run tests
    - name: Install dependencies and run Jest tests
      run: |
        cd jest
        npm install
        npm install @playwright/test
        npx playwright install
        npm install ts-jest @types/jest
        npm run test
        npm run test:ts

    # Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install Pytest dependencies and run tests
    - name: Install dependencies and run Pytest tests
      run: |
        cd pytest
        pip install -r requirements.txt
        pytest -n 2
